# Generated by Django 5.2.1 on 2025-12-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_lectures',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
