# Generated by Django 5.2.1 on 2025-12-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_absent',
            field=models.BooleanField(default=True),
        ),
    ]
